### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by PHactotum**
I've made various updates:

- Change Get-WorkDayWorker -Force to -IncludeInactive (Force is an alias to avoid breaking change)
-Add -IncludeInactive in each Get and Update function
-Fix PSScriptAnalyzer suggested updates:
- where/where-object,
- select/select-object,
- foreach/foreach-object
- Fix UsageType not being retrieved in Get-WorkdayWorkerEmail
- Fix missing commas in the PSD FunctionsToExport Array

I hope these are helpful.

### CODE REVIEW

**Comment by treestryder** [comment]
Thank you. I am a bit underwater, right now, and will try to look at this soon.

**Comment by treestryder** [comment]
I am still under water and unable to address your (very much appreciated) work.

One quick comment, though...

I had looked at using BetterTLS or hard coding the use of stronger encryption into Invoke-WorkdayRequest. In the end, I chose to force older versions of .Net to use the stronger protocols, which is the default behavior of the newer versions of .Net. It was far easier and in my company's best interest. See this Wiki page on how to do this.
https://github.com/treestryder/powershell_module_workdayapi/wiki/SSL-and-TLS-1.0

**Comment by PHactotum** [comment]
No worries.  I had no idea that my commits were continuing to be sent your way.  I, like you, am just trying to make this work for my company.  They are wanting to move to version 32 of the workday api, and I just found that a bunch of stuff is erring.  Seems WD may have changed simple Booleans to 4 ones or 4 zeros.  So, I'll be working that.

I do not mean for my updates to necessarily be absorbed by you. So don't let this pressure you in any way.

**Comment by treestryder** [comment]
@PHactotum Keep the changes coming. The primary hold up is my switching gears from pushing our version to GitHub to pulling a community developed solution and making that work for us.

**Comment by treestryder** [comment]
Merged most of these changes. Thanks again for your help.

**Pull request closed without merging**
