### PR TITLE
Added new function Set-WorkdayWorkerUserName

### PR DESCRIPTION
**Pull request by skumarkom**
## Proposed changes
A new function  **Set-WorkdayWorkerUserName** has been added to update employee/contingent workers username to an email-id

### CODE REVIEW

**Comment by skywayskase** [comment]
I would love to see this get merged as it would benefit our provisioning process. However, in our environment, our usernames _aren't_ email addresses, so ideally I'd prefer the ValidatePattern attribute be removed from the WorkerUserName parameter.

**Comment by treestryder** [comment]
Nice work. I'll try to get to this soon.

And, I do not see any reason not push the User_Name validation off on Workday.

**Comment by treestryder** [comment]
Thank you for your work on this.

**Comment by treestryder** [comment]
After merging and publishing the update to the Powershell Gallery, I just found that what you had called "Username", had been referred to in the code as "UserID", because of it is returned the worker XML as" Worker_Data.User_ID". I am going to switch to UserID, before anyone has time to use the new version.

**Comment by treestryder** [comment]
With an aliased parameter, as after changing it everywhere, I found why you had named it UserName.

Workday_Account_for_Worker_Update.Workday_Account_for_Worker_Data.**User_Name**

**Pull request merged**
