### PR TITLE
Update Invoke-WorkdayRequest.ps1

### PR DESCRIPTION
**Pull request by YuriySamorodov**
Fix error handling in Invoke-WorkdayRequest.ps1

### CODE REVIEW

**Comment by treestryder** [comment]
Sorry. What was wrong with the error handling and how does this fix it?

**Comment by YuriySamorodov** [comment]
Hi, @treestryder 

Without the ```$respStream.position = 0``` I don't get anything in ```$response``` variable. Please see the screenshot:
CleanShot 2024-03-08 at 12 25 45

This is what I am getting after applying the proposed solution:
CleanShot 2024-03-08 at 13 48 19

Hope this will clarify it a bit

**Comment by treestryder** [comment]
It used to work. Haven't had a moment to test this. If this isn't something specific to your use or environment, something must have changed. Before merging this PR, I would like to better understand what is going on and why setting the stream's position to 0 now seems necessary.

**Comment by YuriySamorodov** [comment]
No worries, totally with you. My environment is pretty standard as far as PowerShell is concerned:
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.4046                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.4046}                                               
BuildVersion                   10.0.19041.4046                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```
However, please let me know in case you need more details on this.

**Comment by treestryder** [comment]
I'll be merging this. Not sure why the stream position would not start at 0, but the problem you were seeing exists in my environment as well.
https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-5.0#properties

Thank you for your contribution.

**Pull request merged**
